# DB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/levellog
    username: root
    password: root
    hikari:
      maximum-pool-size: 6

# JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    open-in-view: false

security:
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}

  jwt:
    token:
      secret-key: ${JWT_TOKEN_SECRET}
      expire-length: 360000000

  admin:
    hash: ${ADMIN_HASH}

server:
  tomcat:
    accept-count: 60
    max-connections: 120
    threads:
      max: 8
