spring:
  profiles:
    group:
      "prod": "prod_db, mariadb_dialect"
      "dev":  "test_db, jpa_log, mariadb_dialect"
      "local": "local_db, jpa_log, mariadb_dialect"
      "default": "local_db, jpa_log, mariadb_dialect"

---

spring:
  config:
    activate:
      on-profile: prod_db
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/${PROD_DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${PROD_DB_USER_NAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
        ddl-auto: validate

---

spring:
  config:
    activate:
      on-profile: test_db
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/${TEST_DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${TEST_DB_USER_NAME}
    password: ${TEST_DB_PASSWORD}
  jpa:
    hibernate:
        ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: "local_db"
  datasource:
    url: jdbc:h2:./local_db;MODE=MySQL
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
        ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: "mariadb=dialect"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

---

spring:
  config:
    activate:
      on-profile: "jpa_log"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
