# DB
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:

# JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    username: test@gmail.com
    password: testtesttest
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jasypt:
  encryptor:
    password: test
