name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-build:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          build: yarn build-dev

      - name: Run Cypress tests
        working-directory: ./frontend
        run: yarn test
