name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          browser: chrome

      - name: Check Node v
        run: node -v

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          build: yarn build-dev

      - name: Run Cypress tests
        working-directory: ./frontend
        run: yarn test
