name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2

      - name: Run Cypress tests
        run: yarn test
        continue-on-error: true
