name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build

      - name: Run Cypress tests
        run: yarn test
