name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Check Node v
        run: node -v

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn add cypress

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn add cypress-react-selector

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          runTests: false
          build: yarn build-dev

      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
        run: chrome --version

      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          install: false
          build: yarn test
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/tests/ui/*
