name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-build:
    runs-on: ubuntu-22.04 # 실행 환경 지정
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          runTests: false
          build: yarn build

      - name: Run Cypress tests
        working-directory: ./frontend
        run: yarn test
