name: Cypress Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  cypress-build:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Check Node v
        run: node -v

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn add cypress

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn add cypress-react-selector

#      - name: Cypress install
#        uses: cypress-io/github-action@v4
#        with:
#          working-directory: ./frontend
#          runTests: false
#          build: yarn build-dev

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          install: true
          build: yarn test
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/tests/ui/*
